elasticsearch:
  image: elasticsearch:latest
  command: /bin/bash -c 'usermod -u 1000 elasticsearch; gosu elasticsearch elasticsearch -Des.network.host=0.0.0.0'
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /Users/abhinav/elasticsearch/data:/usr/share/elasticsearch/data
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5044:5044"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
